[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Laenan", email = "me@laenan.de"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.4.8",
]
